(require 'ert)
(ert-deftest a1-type-of-number()
  (message "type-of 2 = %s" (type-of 2))
)
(ert-deftest a1-type-of-string()
  (message "type-of \"hello world\" = %s" (type-of "hello world"))
)
(ert-deftest a1-type-of-list()
  (message "type-of list = %s" (type-of '(rose violet daisy buttercup)))
)
(ert-deftest a2-type-of-flowers()
  (set 'flowers '(rose violet daisy buttercup))
  (message "type-of flowers = %s" (type-of flowers))
)
(ert-deftest a2-set-type-of-flowers()
  (set 'flowers '(rose violet daisy buttercup))
  (message "type-of flowers = %s" (type-of flowers))
)
(ert-deftest a3-setq-type-of-flowers-herbivores()
  (setq flowers '(rose violet daisy buttercup)
       herbivores '(gazelle antelope zebra))
  (message "type-of flowers = %s" (type-of flowers))
  (message "type-of herbivores = %s" (type-of herbivores))  
)
(ert-deftest ax-type-of-fill-column()
  (message "type-of fill-column = %s" (type-of fill-column))
)
