(require 'ert)
(ert-deftest a1-type-of-number()
  (message "type-of 2 = %s" (type-of 2))
)
(ert-deftest a1-type-of-string()
  (message "type-of \"hello world\" = %s" (type-of "hello world"))
)
(ert-deftest a1-type-of-list()
  (message "type-of list = %s" (type-of '(rose violet daisy buttercup)))
)
(ert-deftest a1-type-of-fill-column()
  (message "type-of fill-column = %s" (type-of fill-column))
  )
