(require 'ert)
(ert-deftest t0-how-to-print()
  (let ((msg "t0-how-to-print"))
    (message "message: %s" msg)
    (print "-- print")
    (print msg)
    (print "-- prin1")
    (prin1 msg)
    (print "----- princ")
    (princ msg)
    (print "----- pp")
    (pp msg)
))

;; (ert-deftest t0-hello-world()
;;   (let ((msg "hello world"))
;;     (should (equal msg "hello world"))
;;     (message msg)
;;   )
;; )
;; (ert-deftest t1-list-of-flowers()
;;   (let ((flowers `(rose violet daisy buttercup)))
;;     (message "flowers: %s" flowers)
;;     ))

; stdbuf -i0 -o0 -e0 emacs -batch -l ert -l ert0.el -f ert-run-tests-batch-and-exit
