* meta
** startups
//		#+STARTUP: hidestars	                                                     169-280AD
#+SEQ_TODO: TODO(t!) START(s!) STUCK(k!) WAIT(w!) | DONE(d!) CANCEL(c!) D                 !)
#+PROPERTY: imp_ALL high medium low                                                       
#+PROPERTY: urg_ALL immediate shortterm longterm
#+PROPERTY: loc_ALL home office
#+COLUMNS: %imp %urg %loc
* main
** motivation
The idea is to have one repo for all places to try things etc
** registry
| machine      | os    | directory                |
|--------------+-------+--------------------------|
| air-win10    | win10 | c:\cprojects\github\play |
| kwee1-ubuntu | wsl2  | ~/cprojects/github/play  |
| kwee1-win10  | win10 | d:/cprojects/github/play |
|              |       |                          |
** github password ( do not put here )
A minor change to test push again from air
->air remembers
A minor change to test push from kwee1 win10
Second minor change to confirm password is remembered on kwee1 win10
-> kwee1 win10 remembers
A minor change to test push from kwee1 ubuntu
Second minor change on kwee1 ubuntu to see if remembered
-> kwee1 ubuntu does not remember
Maybe some setup not yet done
Does not bring up the github dialog

Installed git-credential-manager
4th change added
kwee1 ubuntu did not remember
5th change added
kwee1 ubuntu did not remember

So the git-credential-manger is not completely working
> git config --list
user.name=KHT@kwee1-ubuntu
user.email=tan.k.h@juno.com
credential.helper=
credential.helper=/usr/local/bin/git-credential-manager
credential.https://dev.azure.com.usehttppath=true
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/khtan/play.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main

6th change
7th change
** aside : to be transferred
*** classic menu has shutdown if u choose the Win7 style
* projects
** elisp
** [[c:\cprojects\github\play][pw-template ( playwright )]]
create demo and then add the pieces for eslint etc
make corrections per eslint and sonarlint
** dw1 ( playwright/driveway )
*** a/c - be open and clear for this situation
tan.k.h.usa@gmail.com JalanMasuk4!
division of tests folder
   unit
   qe
*** npx playwright codegen www.driveway.com --output x.js
*** DONE use extensions .spec.ts and e2e-spec.ts to distinguish between non gui and gui tests
    CLOSED: [2023-02-16 Thu 15:28]

    - State "DONE"       from "TODO"       [2023-02-16 Thu 15:28]
    - State "TODO"       from              [2023-02-15 Wed 17:14]
*** playwright/test-results.16feb23/loop.org
| Timeout value | Failure run |
|          5000 |           2 |
|        100000 |          14 |
|        200000 | ?           |
Failure after 14 runs
Failure is due to 
net::ERR_ABORTED HEAD https://www.driveway.com/_next/data/auksaRstBdYcp9cFKE2Se/index.json?code=fTpes1uugALz8_B9xUdBJom15IXVgTbM6z2cHB5VNTKxl&state=_NiRDcqbv6ug80zgdc_q74tMhDI3%7EaMb

*** options
1. Each function ( login, logout ) needs a verifying line
2. increase timeout value
3. write a loop that increases the timeout and retests
*** execution context was destroyed
[31m  1) unit\unit.e2e-spec.ts:5:7 › unittests › t0-unitloginlogout [90m====================================[31m[39m

    locator.isVisible: Execution context was destroyed, most likely because of a navigation
    =========================== logs ===========================
      checking visibility of getByRole('button', { name: 'Hi, Kwee' })
    ============================================================

    [90m   at [39m..\common\driveway.ts:37

      35 |       log.info(`${workerIndex} login hiButton not visible. Try # ${retryCount}`);
      36 |       await Utils.delay(1000);
    > 37 |       isVisible = await page.getByRole('button', { name: `Hi, ${username}` }).isVisible();
         |                                                                               ^
      38 |       retryCount += 1;
      39 |     }
      40 |     await expect(page.getByRole('button', { name: `Hi, ${username}` })).toBeVisible();

    [2m    at Function.login (c:\cprojects\github\play\dw1\playwright\common\driveway.ts:37:79)[22m
    [2m    at c:\cprojects\github\play\dw1\playwright\tests\unit\unit.e2e-spec.ts:6:5[22m

[36m    attachment #1: trace (application/zip) [90m---------------------------------------------------------[36m[39m
[36m    playwright\test-results\unit-unit.e2e-spec.ts-unittests-t0-unitloginlogout\trace.zip[39m

This looks like somehow the password was not entered correctly.
The password led remained red

1) After filling the password field, get the value and compare
   By design, password field should not give up its password. Otherwise this is a security problem.
   
2) After filling the password field, check that the LED is green.
   This LED green is not foolproof, so better no rely on it

After reimplementing the navigation:
1. added a waitForLoadState
2. checked for error-icon

The weak spot on button losing context went away. Was able to run until #12 (hrs) without problem.
*** set up on kwee1-ubuntu and run uninterrupted for whole day ( 24 hrs ) to see
*** air: can test parallel login/logout tests





