* meta
** startups
//		#+STARTUP: hidestars	                                                     169-280AD
#+SEQ_TODO: TODO(t!) START(s!) STUCK(k!) WAIT(w!) | DONE(d!) CANCEL(c!) D                 !)
#+PROPERTY: imp_ALL high medium low                                                       
#+PROPERTY: urg_ALL immediate shortterm longterm
#+PROPERTY: loc_ALL home office
#+COLUMNS: %imp %urg %loc
* main
** motivation
The idea is to have one repo for all places to try things etc
** registry
| machine      | os    | directory                |
|--------------+-------+--------------------------|
| air-win10    | win10 | c:\cprojects\github\play |
| kwee1-ubuntu | wsl2  | ~/cprojects/github/play  |
| kwee1-win10  | win10 | d:/cprojects/github/play |
|              |       |                          |
** github password ( do not put here )
A minor change to test push again from air
->air remembers
A minor change to test push from kwee1 win10
Second minor change to confirm password is remembered on kwee1 win10
-> kwee1 win10 remembers
A minor change to test push from kwee1 ubuntu
Second minor change on kwee1 ubuntu to see if remembered
-> kwee1 ubuntu does not remember
Maybe some setup not yet done
Does not bring up the github dialog

Installed git-credential-manager
4th change added
kwee1 ubuntu did not remember
5th change added
kwee1 ubuntu did not remember

So the git-credential-manger is not completely working
> git config --list
user.name=KHT@kwee1-ubuntu
user.email=tan.k.h@juno.com
credential.helper=
credential.helper=/usr/local/bin/git-credential-manager
credential.https://dev.azure.com.usehttppath=true
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/khtan/play.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main

6th change
7th change
** aside : to be transferred
*** classic menu has shutdown if u choose the Win7 style
* projects
** elisp
** [[c:\cprojects\github\play][pw-template ( playwright )]]
create demo and then add the pieces for eslint etc
make corrections per eslint and sonarlint
** dw1 ( playwright/driveway )
*** a/c - be open and clear for this situation
tan.k.h.usa@gmail.com JalanMasuk4!
division of tests folder
   unit
   qe
*** npx playwright codegen www.driveway.com --output x.js
*** DONE use extensions .spec.ts and e2e-spec.ts to distinguish between non gui and gui tests
    CLOSED: [2023-02-16 Thu 15:28]

    - State "DONE"       from "TODO"       [2023-02-16 Thu 15:28]
    - State "TODO"       from              [2023-02-15 Wed 17:14]
*** playwright/test-results.16feb23/loop.org
| Timeout value | Failure run |
|          5000 |           2 |
|        100000 |          14 |
|        200000 | ?           |
Failure after 14 runs
Failure is due to 
net::ERR_ABORTED HEAD https://www.driveway.com/_next/data/auksaRstBdYcp9cFKE2Se/index.json?code=fTpes1uugALz8_B9xUdBJom15IXVgTbM6z2cHB5VNTKxl&state=_NiRDcqbv6ug80zgdc_q74tMhDI3%7EaMb

*** options
1. Each function ( login, logout ) needs a verifying line
2. increase timeout value
3. write a loop that increases the timeout and retests
*** execution context was destroyed
[31m  1) unit\unit.e2e-spec.ts:5:7 › unittests › t0-unitloginlogout [90m====================================[31m[39m

    locator.isVisible: Execution context was destroyed, most likely because of a navigation
    =========================== logs ===========================
      checking visibility of getByRole('button', { name: 'Hi, Kwee' })
    ============================================================

    [90m   at [39m..\common\driveway.ts:37

      35 |       log.info(`${workerIndex} login hiButton not visible. Try # ${retryCount}`);
      36 |       await Utils.delay(1000);
    > 37 |       isVisible = await page.getByRole('button', { name: `Hi, ${username}` }).isVisible();
         |                                                                               ^
      38 |       retryCount += 1;
      39 |     }
      40 |     await expect(page.getByRole('button', { name: `Hi, ${username}` })).toBeVisible();

    [2m    at Function.login (c:\cprojects\github\play\dw1\playwright\common\driveway.ts:37:79)[22m
    [2m    at c:\cprojects\github\play\dw1\playwright\tests\unit\unit.e2e-spec.ts:6:5[22m

[36m    attachment #1: trace (application/zip) [90m---------------------------------------------------------[36m[39m
[36m    playwright\test-results\unit-unit.e2e-spec.ts-unittests-t0-unitloginlogout\trace.zip[39m

This looks like somehow the password was not entered correctly.
The password led remained red

1) After filling the password field, get the value and compare
   By design, password field should not give up its password. Otherwise this is a security problem.
   
2) After filling the password field, check that the LED is green.
   This LED green is not foolproof, so better no rely on it

After reimplementing the navigation:
1. added a waitForLoadState
2. checked for error-icon

The weak spot on button losing context went away. Was able to run until #12 (hrs) without problem.
*** set up on kwee1-ubuntu and run uninterrupted for whole day ( 24 hrs ) to see
**** kwee1-ubuntu needs node and npm 
sudo apt update
sudo apt install nodejs npm 
***** problem: wsl2 path contains /mnt/c stuff that npm accidentally calls
https://stackoverflow.com/questions/67802387/wsl-path-contains-windows-directories-how-to-elegantly-fix-it-to-exclude-only

Fixed:
/home/khtan/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_1.0.3.0_x64__8wekyb3d8bbwe:/mnt/c/ProgramData/Oracle/Java/javapath:/mnt/c/Program Files/Intel/iCLS Client:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/snap/bin:/usr/lib/emacs/27.1/x86_64-linux-gnu
/home/khtan/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib

Had to install google-chrome as well
https://linuxgenie.net/how-to-install-google-chrome-on-ubuntu-22-04/

**** ubuntu npx playwright install not sufficient
sudo apt-get install libdbus-glib-1-2
sudo apt-get install libevent-2.1.7 gstreamer1.0-libav
sudo npx playwright install-deps
**** [[https://askubuntu.com/questions/1444962/cant-install-firefox-in-wsl-since-it-sais-i-need-to-use-snap-but-snap-doesnt][wsl can't install firefox]]
***** steps work
sudo snap remove firefox
sudo apt remove firefox
sudo add-apt-repository ppa:mozillateam/ppa

# Create a new file, it should be empty as it opens:
sudo gedit /etc/apt/preferences.d/mozillateamppa

# Insert these lines, then save and exit
Package: firefox*
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 501

# after saving, do
sudo apt update
sudo apt install firefox

**** wsl install epiphany to get webkit browser on ubuntu
https://www.linuxhelp.com/how-to-install-epiphany-browser-in-ubuntu
https://zoomadmin.com/HowToInstall/UbuntuPackage/epiphany-browser
to install:
   sudo apt update
   sudo apt install epiphany-browser
to invoke:
   epiphany-browser&

**** [[https://linuxhint.com/install-visual-studio-code-ubuntu22-04/][install vs code on ubuntu]]
***** steps
sudo apt update && sudo apt upgrade -y
sudo apt install software-properties-common apt-transport-https wget -y
wget -O- https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor | sudo tee /usr/share/keyrings/vscode.gpg
echo deb [arch=amd64 signed-by=/usr/share/keyrings/vscode.gpg] https://packages.microsoft.com/repos/vscode stable main | sudo tee /etc/apt/sources.list.d/vscode.list
sudo apt update 
sudo apt install code
***** invoke
khtan@kwee1:~/cprojects/github/play/dw1$ code .
To use Visual Studio Code with the Windows Subsystem for Linux, please install Visual Studio Code in Windows and uninstall the Linux version in WSL. You can then use the `code` command in a WSL terminal just as you would in a normal command prompt.
Do you want to continue anyway? [y/N] n
***** ? sudo apt remove code 

*** dw1 run on ubuntu
khtan@kwee1:~/cprojects/github/play/dw1$ npm run test:debug -- --browser=all

> pw1@1.0.0 test:debug /home/khtan/cprojects/github/play/dw1
> npx playwright test -c playwright/config/playwright.config.ts playwright/tests/unit/unit.e2e-spec.ts -g t0 "--browser=all"


Running 3 tests using 2 workers

     1 [chromium] › unit/unit.e2e-spec.ts:5:7 › unittests › t0-unitloginlogout
     2 [firefox] › unit/unit.e2e-spec.ts:5:7 › unittests › t0-unitloginlogout
[2023-02-20T17:31:55.147] [TRACE] driveway - 0 title0: Buying New & Used Cars | Driveway url0:https://www.driveway.com/
[2023-02-20T17:32:00.996] [TRACE] driveway - 0 title1: Buying New & Used Cars | Driveway url1:https://www.driveway.com/
[2023-02-20T17:32:11.714] [TRACE] driveway - 0 title2: Buy or Sell Your Car Your Way | Driveway url2:https://www.driveway.com/post-login
[2023-02-20T17:32:12.322] [INFO] driveway - 0 login Kwee tan.k.h.usa@gmail.com - elapsed: 28364
[2023-02-20T17:32:15.841] [INFO] driveway - 0 logout - elapsed: 3517
end of test
  ✓  1 [chromium] › unit/unit.e2e-spec.ts:5:7 › unittests › t0-unitloginlogout (34.4s)     3 [webkit] › unit/unit.e2e-spec.ts:5:7 › unittests › t0-unitloginlogout

[2023-02-20T17:32:01.181] [TRACE] driveway - 1 title0: Buying New & Used Cars | Driveway url0:https://www.driveway.com/
[2023-02-20T17:32:20.838] [TRACE] driveway - 1 title1: Buy or Sell Your Car Your Way | Driveway url1:https://www.driveway.com/?code=VDv5K0435PyyCkyHZ7FIMtzE4SGv2WV3iJSYcHCXosyNF&state=f_ZOaHD~zMuC-YIhctU--YTxzrQX6nex
[2023-02-20T17:32:30.846] [TRACE] driveway - 1 title2: My Driveway | Driveway url2:https://www.driveway.com/mydriveway
[2023-02-20T17:32:31.233] [INFO] driveway - 1 login Kwee tan.k.h.usa@gmail.com - elapsed: 41921
[2023-02-20T17:32:36.451] [INFO] driveway - 1 logout - elapsed: 5218
end of test
  ✓  2 [firefox] › unit/unit.e2e-spec.ts:5:7 › unittests › t0-unitloginlogout (56.5s)

[2023-02-20T17:32:31.919] [TRACE] driveway - 2 title0: Buying New & Used Cars | Driveway url0:https://www.driveway.com/
[2023-02-20T17:32:45.061] [TRACE] driveway - 2 title1: Buying New & Used Cars | Driveway url1:https://www.driveway.com/
[2023-02-20T17:32:55.982] [TRACE] driveway - 2 title2: Buying New & Used Cars | Driveway url2:https://www.driveway.com/?code=UhaoAVA1QCfRTFswswqEQAubrNx20nundWZyUMEjFI5IZ&state=UcEcYPmvg8QNjBEbtYRkP873iH_Tvhiu
[2023-02-20T17:33:00.383] [INFO] driveway - 2 login Kwee tan.k.h.usa@gmail.com - elapsed: 39815
[2023-02-20T17:33:04.825] [INFO] driveway - 2 logout - elapsed: 4431
end of test
  ✓  3 [webkit] › unit/unit.e2e-spec.ts:5:7 › unittests › t0-unitloginlogout (48.9s)

  3 passed (1.5m)
*** dw1 run on air
c:\cprojects\github\play\dw1>npm run test:debug -- --browser=all

> pw1@1.0.0 test:debug
> npx playwright test -c playwright/config/playwright.config.ts playwright/tests/unit/unit.e2e-spec.ts -g t0 --browser=all


Running 3 tests using 3 workers

  ✓  1 [chromium] › unit\unit.e2e-spec.ts:5:7 › unittests › t0-unitloginlogout (22.1s)
  ✓  2 [firefox] › unit\unit.e2e-spec.ts:5:7 › unittests › t0-unitloginlogout (29.1s)
  ✓  3 [webkit] › unit\unit.e2e-spec.ts:5:7 › unittests › t0-unitloginlogout (43.0s)
[2023-02-20T21:14:38.832] [TRACE] driveway - 0 title0: Buying New & Used Cars | Driveway url0:https://www.driveway.com/
[2023-02-20T21:14:43.063] [TRACE] driveway - 0 title1: Buying New & Used Cars | Driveway url1:https://www.driveway.com/
[2023-02-20T21:14:53.078] [TRACE] driveway - 0 title2: My Driveway | Driveway url2:https://www.driveway.com/mydriveway
[2023-02-20T21:14:53.261] [INFO] driveway - 0 login Kwee tan.k.h.usa@gmail.com - elapsed: 19292
[2023-02-20T21:14:54.543] [INFO] driveway - 0 logout - elapsed: 1282
end of test

[2023-02-20T21:14:40.200] [TRACE] driveway - 1 title0: Buying New & Used Cars | Driveway url0:https://www.driveway.com/
[2023-02-20T21:14:49.681] [TRACE] driveway - 1 title1: Buy or Sell Your Car Your Way | Driveway url1:https://www.driveway.com/?code=g9NyS0z1HGlEw2lK_6NREhJqCTVfZscYhFktOWfFxyVX5&state=0ZCoTv6nfeHoiICeZFHcdCKk9qZh.G45
[2023-02-20T21:14:59.703] [TRACE] driveway - 1 title2: My Driveway | Driveway url2:https://www.driveway.com/mydriveway
[2023-02-20T21:14:59.848] [INFO] driveway - 1 login Kwee tan.k.h.usa@gmail.com - elapsed: 24601
[2023-02-20T21:15:01.606] [INFO] driveway - 1 logout - elapsed: 1758
end of test

[2023-02-20T21:14:47.547] [TRACE] driveway - 2 title0: Buying New & Used Cars | Driveway url0:https://www.driveway.com/
[2023-02-20T21:15:02.214] [TRACE] driveway - 2 title1: Buying New & Used Cars | Driveway url1:https://www.driveway.com/
[2023-02-20T21:15:12.242] [TRACE] driveway - 2 title2: Buy or Sell Your Car Your Way | Driveway url2:https://www.driveway.com/mydriveway
[2023-02-20T21:15:12.420] [INFO] driveway - 2 login Kwee tan.k.h.usa@gmail.com - elapsed: 38404
[2023-02-20T21:15:15.798] [INFO] driveway - 2 logout - elapsed: 3378
end of test


  3 passed (45.8s)

*** air: can test parallel login/logout tests




Something still missing - git-credential-store?

* aside : to be transferred
** classic menu has shutdown if u choose the Win7 style
